export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CAREGIVER = "SET_CAREGIVER";
export const SET_CURRENT_LISTINGS = "SET_CURRENT_LISTINGS";
export const UPDATE_LISTINGS = "UPDATE_LISTINGS";
export const SEARCH_LISTINGS = "SEARCH_LISTINGS";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
